#!/usr/bin/env bash
# Script that transfers a file from client to remote server
if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	filePath=$1
	ip_addr=$2
	username=$3
	ssh_key=$4
	scp -i $ssh_key $filePath $username@$ip_addr:~/
fi