#!/usr/bin/env bash
# Scripts that installs and configures nginx

#Installation
apt-get -y update
apt-get -y install nginx

# Nginx server landing page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure nginx to listen on port 80
sed 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx start