#!/usr/bin/env bash
#You know FizzBuzz right

for ((i = 1; i < 100; i++))
do
    if (($i % 3 == 0 && $i % 5 == 0))
    then
        echo "FizzBuzz"
        continue
    else
        if (($i % 3 == 0))
        then
            echo "Fizz"
            continue
        elif (($i % 5  == 0))
        then
            echo "Buzz"
            continue
        fi
    fi
    echo $i
done