#!/usr/bin/env bash
# while loop:
#   "bad luck" - 4th iteration
#   "good luck" - 8th iteration
#   else "Best School"

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
