#!/usr/bin/env bash
#displays bad luck - 4th loop iteration
#         good luck - 8th loop iteration
#         Best School - other iterations

count=0

while ((count < 10))
do
    if ((count == 3))
    then
        echo "bad luck"
    elif ((count == 7))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done