#!/usr/bin/env bash
#displays bad luck - 4th loop iteration
#         good luck - 8th loop iteration
#         Best School - other iterations

count=0

while ((count < 10))
do
    if ((count == 4))
    then
        echo "bad luck"
    elif ((count == 8))
    then
        echo "good luck"
    fi
    echo "Best School"
    ((count++))
done