#!/usr/bin/env bash
# while loop:
#   "bad luck from China" - 4
#   "bad luck from Japan" - 9
#   "bad luck from Italy" - 17

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
