#!/usr/bin/env bash
#Displays the time for 12 hrs 59 mins

hour=0
mins=1

while ((hour <= 12))
do
    echo "Hour: "$hour
    ((hour++))
    while ((mins < 60))
    do
        echo $mins
        ((mins++))
    done
    ((mins=1))
done